### ISSUE TITLE
BREAKING CHANGES | HomeAssistant 2022-03

### ISSUE THREAD

**Issue by patzobil** [fishbigger/HomeAssistant-Tapo-P100-Control#56] opened 2022-03-29 16:17 UTC
Platform error switch.tapo_p100_control - Requirements for tapo_p100_control not found: ['PyP100==0.0.11'].

**Comment by bryanrossUK** [comment] 2022-03-29 18:08
Duplicate of #54

**Closed as completed** 2022-04-04 11:44 UTC
